@extends('errors.layout')
@section('title', 'Too Many Requests')
@section('code', '429')
@section('heading', 'Slow down for a moment ⏱️')
@section('message', 'You have made a lot of requests in a short time. Please wait a minute and try again.')
